AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  An AWS Serverless Application that uses node running in
  Amazon Lambda.
Parameters: {}
Conditions: {}
Resources:
  ProxyFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'lambda/index.handler'
      Runtime: nodejs8.10
      InlineCode: !Join 
          - |+

          - - '''use strict'';'
            - ''
            - // Greeter Lambda
            - 'exports.handler = (event, context, callback) => {'
            - '  console.log(''Event:'', JSON.stringify(event));'
            - '  const name = event.name || ''World'';'
            - '  const response = {greeting: `Hello, ${name}!`};'
            - '  callback(null, response);'
            - '};'
      MemorySize: 512
      Timeout: 30
      Role: null
      Policies:
        - AWSLambdaFullAccess
      Tracing: Active
      Environment:
        Variables: {}
      Events:
        PutResource:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: ANY
  RootPathFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'lambda/index.handler'
      Runtime: nodejs8.10
      InlineCode: !Join 
          - |+

          - - '''use strict'';'
            - ''
            - // Greeter Lambda
            - 'exports.handler = (event, context, callback) => {'
            - '  console.log(''Event:'', JSON.stringify(event));'
            - '  const name = event.name || ''World'';'
            - '  const response = {greeting: `Hello, ${name}!`};'
            - '  callback(null, response);'
            - '};'
      MemorySize: 512
      Timeout: 30
      Role: null
      Policies:
        - AWSLambdaFullAccess
      Environment:
        Variables: {}
      Events:
        PutResource:
          Type: Api
          Properties:
            Path: /
            Method: ANY
Outputs: {}
